steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'europe-west1-docker.pkg.dev/weighty-diorama-463514-a1/cloud-run-source-deploy/ai-code-agent-adk-image:latest'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'europe-west1-docker.pkg.dev/weighty-diorama-463514-a1/cloud-run-source-deploy/ai-code-agent-adk-image:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'ai-code-agent-adk-service'
  - '--image'
  - 'europe-west1-docker.pkg.dev/weighty-diorama-463514-a1/cloud-run-source-deploy/ai-code-agent-adk-image:latest'
  - '--platform'
  - 'managed'
  - '--region'
  - 'europe-west1'
  - '--allow-unauthenticated'
  - '--service-account'
  - 'ai-code-agent@weighty-diorama-463514-a1.iam.gserviceaccount.com'
  - '--timeout=600s'
  - '--memory=16Gi'
  - '--cpu=4'
  # Remove --set-env-vars here as they are now in Dockerfile
  # If you prefer to keep them here for visibility/override, it's fine,
  # but the Dockerfile is generally where container-specific ENV vars belong.
  env:
  - 'PROJECT_ID=weighty-diorama-463514-a1'

images:
- 'europe-west1-docker.pkg.dev/weighty-diorama-463514-a1/cloud-run-source-deploy/ai-code-agent-adk-image:latest'